services:
  haskell:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: game-of-life
    working_dir: /root/workspace
    volumes:
      - ./:/root/workspace
    tty: true
